[package]
name = "merkle-tree-stream"
description = "A stream that generates a merkle tree based on the incoming data."
version = "0.0.1"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
license = "Apache-2.0"

[dependencies]
futures = "0.1.18"
flat-tree = "1.0.0"

[dev-dependencies]
clippy = "0.0.186"
